import { cn } from "@/shared/lib/utils";
import {
  VscCode,
  VscMenu,
  VscHome,
  VscFile,
  VscFileCode,
  VscFolder,
  VscFolderOpened,
  VscMarkdown,
  VscJson,
  VscRootFolderOpened,
  VscNewFile,
  VscNewFolder,
  VscRefresh,
  VscCollapseAll,
  VscSearch,
  VscTag,
  VscAccount,
  VscOrganization,
  VscSettingsGear,
  VscColorMode,
  VscEllipsis,
  VscChevronDown,
  VscChevronRight,
  VscSourceControl,
  VscPassFilled,
  VscRadioTower,
  VscBell,
  VscCalendar,
  VscEye,
  VscComment,
  VscStarFull,
  VscGithubAlt,
  VscClose,
  VscArrowRight,
  VscArrowLeft,
  VscHistory,
  VscTrash,
  VscSignIn,
  VscSignOut,
  VscBook,
  VscLoading,
  VscCloudDownload,
  VscSend,
  VscEdit,
  VscFileMedia,
  VscSync,
  VscChromeMinimize,
  VscChromeRestore,
  VscChromeMaximize,
  VscChromeClose,
} from "react-icons/vsc";

export const Icons = {
  logo: VscCode,
  menu: VscMenu,
  home: VscHome,
  posts: VscFile,
  files: VscFile,
  explorer: VscFolderOpened,
  search: VscSearch,
  tags: VscTag,
  user: VscAccount,
  users: VscOrganization,
  settings: VscSettingsGear,
  moon: VscColorMode,
  sun: VscColorMode,
  more: VscEllipsis,
  chevronDown: VscChevronDown,
  chevronRight: VscChevronRight,
  gitBranch: VscSourceControl,
  check: VscPassFilled,
  wifi: VscRadioTower,
  bell: VscBell,
  calendar: VscCalendar,
  eye: VscEye,
  comment: VscComment,
  messageSquare: VscComment,
  star: VscStarFull,
  github: VscGithubAlt,
  close: VscClose,
  fileCode: VscFileCode,
  arrowRight: VscArrowRight,
  arrowLeft: VscArrowLeft,
  clock: VscHistory,
  trash: VscTrash,
  folder: VscFolder,
  logIn: VscSignIn,
  logOut: VscSignOut,
  velog: VscBook,
  loading: VscLoading,
  loader: VscLoading,
  download: VscCloudDownload,
  send: VscSend,
  edit: VscEdit,
  image: VscFileMedia,
  markdown: VscMarkdown,
  json: VscJson,
  folderOpen: VscFolderOpened,
  rootFolderOpen: VscRootFolderOpened,
  newFile: VscNewFile,
  newFolder: VscNewFolder,
  refresh: VscRefresh,
  collapseAll: VscCollapseAll,
  sync: VscSync,
  windowMinimize: VscChromeMinimize,
  windowRestore: VscChromeRestore,
  windowMaximize: VscChromeMaximize,
  windowClose: VscChromeClose,
};

export type IconKey = keyof typeof Icons;

interface IconProps extends React.ComponentProps<"svg"> {
  name: IconKey;
}

export function Icon({ name, className, ...props }: IconProps) {
  const CodIcon = Icons[name];

  if (!CodIcon) {
    return null;
  }

  return <CodIcon className={cn("w-4 h-4", className)} {...props} />;
}
